using Gibag.Modules.Sales.Domain;
using Gibag.Shared.Models;
using MediatR;

namespace Gibag.Modules.Sales.Application.Sales.CreateSale;

public record CreateSaleCommand(
    Guid Id, // Optional Guid generated by Frontend
    Guid SessionId,
    Guid BranchId,
    decimal SubTotal,
    decimal Tax,
    decimal Total,
    decimal Discount, // Total discount (percentage or fixed amount calculated on frontend)
    DateTimeOffset? CreatedAt,
    List<CreateSaleDetailDto> Details,
    List<CreateSalePaymentDto> Payments
) : IRequest<Result<Guid>>;

public record CreateSaleDetailDto(
    Guid Id, 
    Guid ProductId,
    decimal Quantity,
    decimal UnitPrice,
    decimal DiscountAmount = 0m // Optional: discount per item
);

public record CreateSalePaymentDto(
    Guid Id,
    decimal Amount,
    PaymentMethod Method
);
